ROUTINE day07p2
 ;day07.txt
 K  S B=+$G(B),C='B,D=C+C,Q=$E($ZV,D),A=$E($ZV,D+D),F=$E($T(+C),D+C,*),K=$C($A(Q)+(C_D)),$ZT=Q
 O F:Q U F F  R S S W=$L(S) D $I(I) S G=B,H=$F(S,A) S:H J(I,H-C)=C F  S G=$F(S,K,G) Q:G=B  S I(I,G-C)=C
R C F F M=D:C:I F N=C:C:W I $G(J(M-C,N)) S P=J(M-C,N) D $I(J(M,N),P) D
 .I $G(I(M,N)) K J(M,N) D:'$G(I(M,N-C)) $I(J(M,N-C),P) D:'$G(I(M,N+C)) $I(J(M,N+C),P)
 S Z=B F  S Z=$O(J(I,Z)) Q:'Z  D $I(Y,J(I,Z))
 W Y